### ISSUE TITLE
not compatible with angular 15

### ISSUE THREAD

**Issue by berndhopp** [bluehalo/ngx-leaflet-draw#134]

**Comment by nutangwari** [comment]
here is the error while installing ngx-leaflet-* package:

`
npm i @asymmetrik/ngx-leaflet --save             
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: headsup_ionic_6@0.0.1
npm WARN Found: @asymmetrik/ngx-leaflet@14.0.1
npm WARN node_modules/@asymmetrik/ngx-leaflet
npm WARN   peer @asymmetrik/ngx-leaflet@"14" from @asymmetrik/ngx-leaflet-draw@14.0.1
npm WARN   node_modules/@asymmetrik/ngx-leaflet-draw
npm WARN     @asymmetrik/ngx-leaflet-draw@"^14.0.1" from the root project
npm WARN   1 more (the root project)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @asymmetrik/ngx-leaflet@"14" from @asymmetrik/ngx-leaflet-draw@14.0.1
npm WARN node_modules/@asymmetrik/ngx-leaflet-draw
npm WARN   @asymmetrik/ngx-leaflet-draw@"^14.0.1" from the root project
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @asymmetrik/ngx-leaflet-draw@14.0.1
npm ERR! Found: @angular/common@15.1.5
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@"15.1.5" from @angular/forms@15.1.5
npm ERR!   node_modules/@angular/forms
npm ERR!     peer @angular/forms@">=12.0.0" from @ionic/angular@6.5.2
npm ERR!     node_modules/@ionic/angular
npm ERR!       @ionic/angular@"^6.1.9" from the root project
npm ERR!     @angular/forms@"^15.1.5" from the root project
npm ERR!   peer @angular/common@"^14.0.0 || ^15.0.0" from @angular/google-maps@14.2.7
npm ERR!   node_modules/@angular/google-maps
npm ERR!     @angular/google-maps@"^14.0.0" from the root project
npm ERR!   5 more (@angular/platform-browser, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"14" from @asymmetrik/ngx-leaflet-draw@14.0.1
npm ERR! node_modules/@asymmetrik/ngx-leaflet-draw
npm ERR!   @asymmetrik/ngx-leaflet-draw@"^14.0.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/common@14.2.12
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@"14" from @asymmetrik/ngx-leaflet-draw@14.0.1
npm ERR!   node_modules/@asymmetrik/ngx-leaflet-draw
npm ERR!     @asymmetrik/ngx-leaflet-draw@"^14.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\nutan\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nutan\AppData\Local\npm-cache\_logs\2023-02-20T19_03_53_849Z-debug-0.log
`

**Comment by reblace** [comment]
Just released v15
