### ISSUE TITLE
`LeafletDrawModule` is not exported correctly

### ISSUE THREAD

**Issue by royvanv** [bluehalo/ngx-leaflet-draw#143]
I am using version 15.0.0, but it is not working correctly for me.

When importing the `LeafletDrawModule ` I get the following error: `Cannot find module '@asymmetrik/ngx-leaflet-draw' or its corresponding type declarations.ts(2307)`.

```typescript
import { LeafletDrawModule } from '@asymmetrik/ngx-leaflet-draw';
```

**Comment by mateustormin** [comment]
got the same error after updating and existing working project

**Comment by reblace** [comment]
Not sure what happened with the npm publish for 15.0.0, just republished with 15.0.1. Should be fixed.
